// Design note: Sirkuit Editorial — community projects read like field notes, with build labels, tactile imagery, and asymmetrical gallery rhythm.
import { ArrowDownToLine, ArrowRight, BookOpen, Download, Heart, Layers3, Users } from "lucide-react";
import { useState } from "react";
import { projects } from "@/lib/content";
import FileStorageUploader from "@/components/FileStorageUploader";
import { Button } from "@/components/ui/button";

export default function Projects() {
  const [level, setLevel] = useState("Semua");
  const shown = level === "Semua" ? projects : projects.filter((p) => p.level === level);
  return <div>
    <section className="page-intro"><div className="container grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="eyebrow mb-5"><span className="signal-dot" /> 05 / Community builds</p><h1 className="page-title">Bukan cuma melihat. <span>Ikut membangun.</span></h1></div><p className="max-w-md text-base leading-7 text-muted-foreground">Build log dari maker Indonesia: lengkap dengan komponen, proses perakitan, dan sketch untuk kamu kembangkan.</p></div></section>
    <section className="container py-14"><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2">{["Semua", "Pemula", "Menengah", "Mahir"].map((x) => <button key={x} onClick={() => setLevel(x)} className={`filter-pill ${level === x ? "filter-pill-active" : ""}`}>{x}</button>)}</div><div className="flex items-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Users className="size-4 text-primary" /> 2.4k builder</span><span className="flex items-center gap-2"><Layers3 className="size-4 text-primary" /> 120+ build log</span></div></div><div className="grid gap-5 lg:grid-cols-2">{shown.map((project, i) => <article key={project.id} className={`community-card ${i === 0 ? "lg:col-span-2 lg:grid lg:grid-cols-[1.1fr_.9fr]" : ""}`}><div className="relative min-h-[260px] overflow-hidden bg-muted"><img src={project.image} alt={project.title} className="absolute inset-0 size-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-5 top-5 rounded-full bg-orange px-3 py-1.5 text-[10px] font-extrabold tracking-[.12em] text-graphite">{project.label}</span></div><div className="flex flex-col justify-between p-6 sm:p-8"><div><div className="flex items-center justify-between"><span className="eyebrow text-primary">{project.level} / {project.parts}</span><Heart className="size-4 text-muted-foreground" /></div><h2 className="mt-6 text-2xl font-extrabold tracking-tight">{project.title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{project.description}</p></div><div className="mt-8 flex flex-wrap gap-2"><Button variant="outline" className="rounded-full text-xs"><BookOpen className="mr-2 size-3.5" /> Panduan rakit</Button><Button variant="outline" className="rounded-full text-xs"><Download className="mr-2 size-3.5" /> Unduh sketch</Button></div></div></article>)}</div></section><section className="container py-16"><FileStorageUploader /></section><section className="container pb-24"><div className="relative overflow-hidden rounded-[2rem] border border-primary/20 bg-primary/10 p-8 sm:p-12"><div className="relative z-10 max-w-2xl"><p className="eyebrow text-primary">Share your build</p><h2 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">Proyekmu bisa jadi langkah pertama orang lain.</h2><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Dokumentasikan rangkaian, ceritakan bagian yang gagal, lalu kirim build log-mu ke komunitas.</p><Button className="mt-7 rounded-full">Kirim build log <ArrowRight className="ml-2 size-4" /></Button></div><div className="absolute -right-12 -top-12 size-64 rounded-full border border-primary/20" /></div></section>
  </div>;
}
