// Design note: Sirkuit Editorial — product catalog feels like a curated parts counter, balancing practical BOM metadata with editorial product hierarchy.
import { useMemo, useState } from "react";
import { ArrowRight, Check, Package, Search, ShoppingBag, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatRupiah, products } from "@/lib/content";

const categories = ["Semua", "Kit Robot", "Board", "Sensor", "Servo", "Chassis", "Motor Driver"];
export default function Shop() {
  const [category, setCategory] = useState("Semua");
  const [query, setQuery] = useState("");
  const [onlyStock, setOnlyStock] = useState(false);
  const shown = useMemo(() => products.filter((p) => (category === "Semua" || p.category === category) && (!onlyStock || p.stock > 0) && p.name.toLowerCase().includes(query.toLowerCase())), [category, query, onlyStock]);
  return <div>
    <section className="page-intro"><div className="container grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="eyebrow mb-5"><span className="signal-dot" /> 06 / Parts counter</p><h1 className="page-title">Komponen yang tepat untuk <span>build berikutnya.</span></h1></div><p className="max-w-md text-base leading-7 text-muted-foreground">Kurasi board, sensor, motor, dan kit yang mengikuti jalur tutorial—supaya kamu bisa fokus merakit, bukan menebak BOM.</p></div></section>
    <section className="container py-14"><div className="shop-toolbar"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari board, sensor, kit..." className="h-11 w-full rounded-xl border border-border bg-background pl-10 text-sm outline-none ring-primary transition focus:ring-2" /></div><button onClick={() => setOnlyStock(!onlyStock)} className={`filter-pill ${onlyStock ? "filter-pill-active" : ""}`}><SlidersHorizontal className="mr-2 size-3.5" /> Ready stock</button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><ShoppingBag className="size-4" /> 0 item</div></div><div className="mt-7 flex gap-2 overflow-x-auto pb-2">{categories.map((x) => <button key={x} onClick={() => setCategory(x)} className={`filter-pill whitespace-nowrap ${category === x ? "filter-pill-active" : ""}`}>{x}</button>)}</div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{shown.map((product, i) => <article key={product.id} className="product-card animate-rise" style={{ animationDelay: `${i * 45}ms` }}><div className={`product-visual product-visual-${product.color}`}><span className="eyebrow text-white/75">{product.tag}</span><div className="schematic-label">BOM / {product.id.toUpperCase()}</div><div className={`component-silhouette component-${product.category.toLowerCase().replaceAll(" ", "-")}`}><span /><span /><span /></div><div className="trace trace-a" /><div className="trace trace-b" /></div><div className="p-5"><div className="flex items-center justify-between"><span className="eyebrow text-muted-foreground">{product.category}</span>{product.stock > 0 ? <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-600"><Check className="size-3" /> {product.stock} stok</span> : <span className="text-[10px] font-bold text-orange">Pre-order</span>}</div><h2 className="mt-4 text-lg font-extrabold tracking-tight">{product.name}</h2><div className="mt-6 flex items-end justify-between gap-3"><div><p className="text-lg font-extrabold text-primary">{formatRupiah(product.price)}</p><p className="mt-1 text-[11px] text-muted-foreground">Belum termasuk ongkir</p></div><Button disabled={product.stock === 0} size="sm" className="rounded-full text-xs">{product.stock > 0 ? "Tambah" : "Ingatkan saya"} <ArrowRight className="ml-1.5 size-3.5" /></Button></div></div></article>)}</div>{shown.length === 0 && <div className="empty-state"><Package className="mx-auto size-8 text-primary" /><p className="mt-4 font-bold">Belum ada komponen di jalur ini.</p><p className="mt-1 text-sm text-muted-foreground">Coba ubah filter atau kata pencarian.</p></div>}</section>
  </div>;
}
