// Design note: Sirkuit Editorial — tutorial index is a technical editorial desk with filters, BOM cues, and code-first reading paths.
import { useMemo, useState } from "react";
import { Check, Clipboard, Code2, Filter, GitBranch, Play, Search, Wrench } from "lucide-react";
import { tutorials, sampleTutorialJson } from "@/lib/content";
import { Button } from "@/components/ui/button";

const categories = ["Semua kategori", "Robotika", "IoT", "Sensor", "Motor Driver"];
const levels = ["Semua level", "Pemula", "Menengah", "Mahir"];

export default function Tutorials() {
  const [level, setLevel] = useState("Semua level");
  const [category, setCategory] = useState("Semua kategori");
  const [copied, setCopied] = useState(false);
  const filtered = useMemo(() => tutorials.filter((t) => (level === "Semua level" || t.difficulty === level) && (category === "Semua kategori" || t.category === category)), [level, category]);
  const copyCode = async () => { await navigator.clipboard?.writeText(sampleTutorialJson.code); setCopied(true); setTimeout(() => setCopied(false), 1600); };
  return <div>
    <section className="page-intro"><div className="container grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="eyebrow mb-5"><span className="signal-dot" /> 04 / Knowledge base</p><h1 className="page-title">Tutorial yang membuat teori <span>jadi gerak.</span></h1></div><p className="max-w-md text-base leading-7 text-muted-foreground">Jalur belajar modular untuk membaca sensor, mengendalikan motor, dan menyusun robot yang bisa kamu pahami dari kabel pertama.</p></div></section>
    <section className="container py-14"><div className="filter-bar"><div className="flex items-center gap-2 text-sm font-bold"><Filter className="size-4 text-primary" /> Filter jalur</div><select value={level} onChange={(e) => setLevel(e.target.value)} className="select-control">{levels.map((x) => <option key={x}>{x}</option>)}</select><select value={category} onChange={(e) => setCategory(e.target.value)} className="select-control">{categories.map((x) => <option key={x}>{x}</option>)}</select><span className="ml-auto text-xs text-muted-foreground">{filtered.length} tutorial ditemukan</span></div><div className="mt-8 grid gap-4 md:grid-cols-2">{filtered.map((tutorial, i) => <article key={tutorial.id} className="tutorial-card animate-rise" style={{ animationDelay: `${i * 50}ms` }}><div className="flex items-center justify-between"><span className={`signal-chip signal-chip-${tutorial.accent}`}>{tutorial.category}</span><span className="eyebrow text-muted-foreground">{tutorial.difficulty}</span></div><h2 className="mt-8 max-w-md text-xl font-extrabold tracking-tight">{tutorial.title}</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">{tutorial.excerpt}</p><div className="mt-8 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Wrench className="size-3.5" /> {tutorial.duration}</span><span className="flex items-center gap-1.5"><Play className="size-3.5" /> {tutorial.readTime} baca</span><Button variant="ghost" size="sm" className="-mr-2 text-primary">Buka <GitBranch className="ml-1 size-3.5" /></Button></div></article>)}</div></section>
    <section className="border-y border-border bg-graphite py-16 text-white"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-orange">Tutorial anatomy / sample</p><h2 className="mt-4 text-3xl font-extrabold tracking-tight">Satu halaman. Semua yang dibutuhkan.</h2><p className="mt-4 max-w-sm text-sm leading-7 text-white/60">Setiap tutorial punya BOM, slot skematik, dan kode yang siap kamu salin ke Arduino IDE.</p><div className="mt-8 space-y-3 text-sm text-white/75"><div className="flex items-center gap-3"><span className="step-number">01</span> Bill of Materials</div><div className="flex items-center gap-3"><span className="step-number">02</span> Diagram rangkaian</div><div className="flex items-center gap-3"><span className="step-number">03</span> Kode C++ dengan copy action</div></div></div><div className="code-window"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex items-center gap-2"><span className="window-dot bg-[#ff6b5e]" /><span className="window-dot bg-[#f9c74f]" /><span className="window-dot bg-[#43d17a]" /><span className="ml-3 text-[11px] text-white/45">robot-obstacle-avoider.ino</span></div><Button variant="ghost" size="sm" onClick={copyCode} className="h-8 text-xs text-white/70 hover:bg-white/10 hover:text-white">{copied ? <Check className="mr-1.5 size-3.5 text-green-400" /> : <Clipboard className="mr-1.5 size-3.5" />}{copied ? "Tersalin" : "Copy code"}</Button></div><pre className="overflow-x-auto p-5 text-[12px] leading-7 text-cyan-100"><code>{sampleTutorialJson.code}</code></pre></div></div></section>
  </div>;
}
